"""Pydantic request / response schemas used across the API layer.

Every model uses strict validation so callers get clear errors when they send
malformed payloads.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional
from uuid import uuid4

from pydantic import BaseModel, Field


# ═══════════════════════════════════════════════════════════════════════════════
# Request models
# ═══════════════════════════════════════════════════════════════════════════════


class ChatRequest(BaseModel):
    """Inbound chat question from the user.

    If ``session_id`` is omitted the server will generate one so that
    follow-up messages can be correlated.
    """

    question: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Natural-language question from the user.",
    )
    session_id: Optional[str] = Field(
        default=None,
        description=(
            "Optional session identifier.  "
            "When absent the server creates a new session."
        ),
    )

    def resolve_session_id(self) -> str:
        """Return the existing session id or mint a new UUID-4."""
        return self.session_id or uuid4().hex


# ═══════════════════════════════════════════════════════════════════════════════
# Response models
# ═══════════════════════════════════════════════════════════════════════════════


class ChatResponse(BaseModel):
    """Complete response returned to the caller after the pipeline finishes."""

    question: str = Field(
        ..., description="Original question echoed back for convenience."
    )
    answer: str = Field(
        ..., description="Natural-language answer generated by the LLM."
    )
    sql: Optional[str] = Field(
        default=None,
        description="Generated SQL query (if applicable).",
    )
    results: Optional[list[dict[str, Any]]] = Field(
        default=None,
        description="Raw result rows returned by the SQL query.",
    )
    tables_used: list[str] = Field(
        default_factory=list,
        description="List of table names referenced in the query.",
    )
    intent: Optional[str] = Field(
        default=None,
        description="Classified intent (COUNT, LIST, AGGREGATE, …).",
    )
    entities: Optional[dict[str, Any]] = Field(
        default=None,
        description="Extracted business entities.",
    )
    execution_time_ms: float = Field(
        ...,
        description="Wall-clock time for the entire pipeline in milliseconds.",
    )
    session_id: Optional[str] = Field(
        default=None, description="Session identifier for follow-ups."
    )


class HealthResponse(BaseModel):
    """Lightweight health-check payload."""

    status: str = Field(
        default="healthy", description="Overall health status."
    )
    version: str = Field(default="1.0.0", description="Application version.")
    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="Server UTC timestamp.",
    )
    services: dict[str, bool] = Field(
        default_factory=dict,
        description="Per-service reachability map.",
    )


class WebSocketMessage(BaseModel):
    """Envelope used for all WebSocket frames (both directions).

    ``type`` values include:
    - ``question``   — client sends a new question
    - ``thinking``   — server streams intermediate progress
    - ``sql``        — server sends the generated SQL
    - ``result``     — server sends the final answer
    - ``error``      — server reports an error
    """

    type: str = Field(
        ...,
        description="Message type discriminator.",
    )
    message: str = Field(
        ...,
        description="Human-readable payload.",
    )
    data: Optional[dict[str, Any]] = Field(
        default=None,
        description="Optional structured data accompanying the message.",
    )
